name: Repository Sync

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/igm4ai
        dst: gitee/igm4ai
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        static_list: "template-simple"
        force_update: true
